# FLASK
HOST = '0.0.0.0'

# FLASK-BASICAUTH
BASIC_AUTH_FORCE = True

# FLASK-SESSION
PERMANENT_SESSION_LIFETIME = 60000000

# FLASK-SQLALCHEMY
SQLALCHEMY_DATABASE_URI = 'sqlite:///data/production.sqlite'
